name: 프로덕션 테스트

on:
  workflow_dispatch:
    inputs:
      build_run_id:
        description: "Build Workflow Run ID"
        required: true
        type: string
      pr_number:
        description: 'PR Number'
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: test
        env:
          BUILD_RUN_ID: ${{ github.event.inputs.build_run_id }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
        run: |
          echo "빌드 워크플로우 Run ID: ${BUILD_RUN_ID}"
          echo "PR 번호: ${PR_NUMBER}"